# Generated by Django 4.2.9 on 2024-01-30 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SipgateUser',
            fields=[
                ('sipgate_user', models.CharField(default=None, max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('alias_name', models.CharField(max_length=255)),
                ('SipgateUserToken', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('sipgate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.sipgateuser')),
            ],
        ),
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_on', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('call_type', models.BooleanField(default=False)),
                ('sipgate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.sipgateuser')),
            ],
        ),
    ]
