# Generated by Django 5.0.1 on 2024-02-02 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255, null=True)),
                ('from_number', models.CharField(max_length=15, null=True)),
                ('to_number', models.CharField(max_length=15, null=True)),
                ('direction', models.CharField(blank=True, max_length=10, null=True)),
                ('call_id', models.CharField(max_length=255, null=True)),
                ('user', models.CharField(max_length=255, null=True)),
                ('user_id_list', models.CharField(max_length=255, null=True)),
                ('user_id_list1', models.CharField(max_length=255, null=True)),
                ('full_user_id_list', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('caller_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SipgateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sipgate_user', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('caller', models.CharField(max_length=255, null=True)),
                ('alias_name', models.CharField(max_length=255)),
                ('sipgate_user_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('called_on_number', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_type', models.BooleanField(default=False)),
                ('caller', models.CharField(blank=True, max_length=255, null=True)),
                ('caller_id', models.CharField(blank=True, max_length=255, null=True)),
                ('device', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Myapp.devices')),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='sipgate_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myapp.sipgateuser'),
        ),
    ]
