# Generated by Django 4.2.9 on 2024-01-30 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycontacts',
            old_name='sipgate_user',
            new_name='sipgate_use',
        ),
    ]
