# Generated by Django 4.2.9 on 2024-01-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_rename_sipgate_use_companycontacts_sipgate_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('from_number', models.CharField(max_length=15)),
                ('to_number', models.CharField(max_length=15)),
                ('direction', models.CharField(max_length=10)),
                ('call_id', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('user_id_list', models.CharField(max_length=255)),
                ('user_id_list1', models.CharField(max_length=255)),
                ('full_user_id_list', models.CharField(max_length=255)),
            ],
        ),
    ]
