# Generated by Django 4.2.9 on 2024-01-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='direction',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
